services:
  - type: web
    name: hrhelp
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    autoDeploy: true
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "False"
